export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed-dim": "#d8c598",
        "secondary-container": "#e2e2e2",
        "surface": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "on-primary-fixed-variant": "#004785",
        "on-tertiary-container": "#4b3e1c",
        "surface-container": "#edeeef",
        "surface-tint": "#005fae",
        "outline-variant": "#c1c7d4",
        "secondary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#001c3a",
        "on-secondary-fixed-variant": "#474747",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-surface-variant": "#414752",
        "on-secondary-fixed": "#1b1b1b",
        "outline": "#717783",
        "surface-container-high": "#e7e8e9",
        "on-surface": "#191c1d",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-fixed-variant": "#534523",
        "primary-container": "#0072ce",
        "inverse-surface": "#2e3132",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9fa",
        "primary-fixed": "#d4e3ff",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "secondary": "#5e5e5e",
        "on-tertiary-fixed": "#241a00",
        "on-primary-container": "#f4f6ff",
        "secondary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#a5c8ff",
        "on-background": "#191c1d",
        "inverse-primary": "#a5c8ff",
        "primary": "#0059a4",
        "tertiary": "#6c5d38",
        "tertiary-fixed": "#f5e1b2",
        "tertiary-container": "#bcaa7f",
        "on-secondary-container": "#646464",
        "surface-container-low": "#f3f4f5",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "background": "#f8f9fa"
      },
      "fontFamily": {
        "headline": ["Manrope"],
        "body": ["Public Sans"],
        "label": ["Public Sans"]
      }
    },
  },
  plugins: [],
}
